#!/usr/bin/env bash

SCRIPT_DIRECTORY=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

docker-compose --file "$SCRIPT_DIRECTORY/docker-compose.yml" build --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g)
