version: "3.8"
services:
  spacemacs-application:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
      - SPACEMACS_DOCKER_CONTAINER=true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./install-spacemacs:/home/spacemacs/install-spacemacs
      - spacemacs-.emacs.d-volume:/home/spacemacs/.emacs.d
      - ./.spacemacs.d:/home/spacemacs/.spacemacs.d
      - ./org:/home/spacemacs/org
    network_mode: host
volumes:
  spacemacs-.emacs.d-volume:
