#!/usr/bin/env bash

shopt -s dotglob

if [[ "$SPACEMACS_DOCKER_CONTAINER"  == "true" ]]; then
  if [[ -d "$HOME/.emacs.d" ]] ; then
    rm -rf "$HOME/.emacs.d"/*
    git clone -b develop https://github.com/syl20bnr/spacemacs "$HOME/.emacs.d"
  fi
fi
